# Generated by Django 4.1.7 on 2023-03-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='get_Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field_name', models.FileField(help_text='Enter field documentation', upload_to='')),
            ],
            options={
                'ordering': ['-my_field_name'],
            },
        ),
    ]
